export type Band = "FM" | "AM";

export type Station = {
  id: string;
  name: string;
  callsign: string;
  frequency: number;
  band: Band;
  city: string;
  genre: string;
  streamUrl: string;
};

export const stations: Station[] = [
  {
    id: "bbc-r1",
    name: "BBC Radio 1",
    callsign: "BBC R1",
    frequency: 97.7,
    band: "FM",
    city: "London",
    genre: "Pop",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
  },
  {
    id: "bbc-r2",
    name: "BBC Radio 2",
    callsign: "BBC R2",
    frequency: 88.1,
    band: "FM",
    city: "London",
    genre: "Adult contemporary",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
  },
  {
    id: "bbc-r4",
    name: "BBC Radio 4",
    callsign: "BBC R4",
    frequency: 92.5,
    band: "FM",
    city: "London",
    genre: "Talk",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm",
  },
  {
    id: "bbc-r6",
    name: "BBC Radio 6 Music",
    callsign: "BBC 6",
    frequency: 99.3,
    band: "FM",
    city: "London",
    genre: "Alternative",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
  },
  {
    id: "bbc-ws",
    name: "BBC World Service",
    callsign: "BBC WS",
    frequency: 648,
    band: "AM",
    city: "London",
    genre: "News",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service",
  },
  {
    id: "kexp",
    name: "KEXP 90.3",
    callsign: "KEXP",
    frequency: 90.3,
    band: "FM",
    city: "Seattle",
    genre: "Indie",
    streamUrl: "https://kexp.streamguys1.com/kexp160.aac",
  },
  {
    id: "wnyc",
    name: "WNYC",
    callsign: "WNYC",
    frequency: 93.9,
    band: "FM",
    city: "New York",
    genre: "Public radio",
    streamUrl: "https://fm939.wnyc.org/wnycfm",
  },
  {
    id: "npr",
    name: "NPR News",
    callsign: "NPR",
    frequency: 103.5,
    band: "FM",
    city: "Washington",
    genre: "News",
    streamUrl: "https://npr-ice.streamguys1.com/live.mp3",
  },
  {
    id: "soma-groove",
    name: "SomaFM Groove Salad",
    callsign: "SOMA GS",
    frequency: 101.1,
    band: "FM",
    city: "San Francisco",
    genre: "Ambient",
    streamUrl: "https://ice1.somafm.com/groovesalad-128-mp3",
  },
  {
    id: "soma-drone",
    name: "SomaFM Drone Zone",
    callsign: "SOMA DZ",
    frequency: 105.7,
    band: "FM",
    city: "San Francisco",
    genre: "Drone",
    streamUrl: "https://ice1.somafm.com/dronezone-128-mp3",
  },
  {
    id: "soma-beat",
    name: "SomaFM Beat Blender",
    callsign: "SOMA BB",
    frequency: 96.3,
    band: "FM",
    city: "San Francisco",
    genre: "Downtempo",
    streamUrl: "https://ice1.somafm.com/beatblender-128-mp3",
  },
  {
    id: "soma-defcon",
    name: "SomaFM DEF CON",
    callsign: "SOMA DC",
    frequency: 107.9,
    band: "FM",
    city: "San Francisco",
    genre: "Electronic",
    streamUrl: "https://ice1.somafm.com/defcon-128-mp3",
  },
  {
    id: "fip",
    name: "FIP",
    callsign: "FIP",
    frequency: 105.1,
    band: "FM",
    city: "Paris",
    genre: "Eclectic",
    streamUrl: "https://icecast.radiofrance.fr/fip-midfi.mp3",
  },
  {
    id: "france-inter",
    name: "France Inter",
    callsign: "INTER",
    frequency: 87.8,
    band: "FM",
    city: "Paris",
    genre: "Talk",
    streamUrl: "https://icecast.radiofrance.fr/franceinter-midfi.mp3",
  },
  {
    id: "nts",
    name: "NTS Live 1",
    callsign: "NTS",
    frequency: 98.5,
    band: "FM",
    city: "London",
    genre: "Underground",
    streamUrl: "https://stream-relay-geo.ntslive.net/stream",
  },
  {
    id: "kcrw",
    name: "KCRW",
    callsign: "KCRW",
    frequency: 89.9,
    band: "FM",
    city: "Los Angeles",
    genre: "Eclectic",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_on_air",
  },
  {
    id: "wfmu",
    name: "WFMU",
    callsign: "WFMU",
    frequency: 91.1,
    band: "FM",
    city: "Jersey City",
    genre: "Freeform",
    streamUrl: "https://stream0.wfmu.org/freeform-128k",
  },
  {
    id: "classic-fm",
    name: "Classic FM",
    callsign: "CLSC FM",
    frequency: 100.0,
    band: "FM",
    city: "London",
    genre: "Classical",
    streamUrl: "https://media-ice.musicradio.com/ClassicFMMP3",
  },
  {
    id: "lbc",
    name: "LBC",
    callsign: "LBC",
    frequency: 97.3,
    band: "FM",
    city: "London",
    genre: "Talk",
    streamUrl: "https://media-ice.musicradio.com/LBCUKMP3",
  },
  {
    id: "am-news",
    name: "WNYC AM 820",
    callsign: "WNYC AM",
    frequency: 820,
    band: "AM",
    city: "New York",
    genre: "News",
    streamUrl: "https://am820.wnyc.org/wnycam",
  },
  {
    id: "am-talk",
    name: "Talk Radio",
    callsign: "TALK",
    frequency: 1089,
    band: "AM",
    city: "London",
    genre: "Talk",
    streamUrl: "https://radio.talkradio.co.uk/stream",
  },
  {
    id: "am-world",
    name: "RNZ National",
    callsign: "RNZ",
    frequency: 567,
    band: "AM",
    city: "Wellington",
    genre: "Public radio",
    streamUrl: "https://radionz-ice.streamguys1.com/national.mp3",
  },
  {
    id: "am-abc",
    name: "ABC Radio National",
    callsign: "ABC RN",
    frequency: 576,
    band: "AM",
    city: "Sydney",
    genre: "Talk",
    streamUrl: "https://live-radio01.mediahubaustralia.com/2RNW/mp3/",
  },
  {
    id: "jazz24",
    name: "SomaFM Folk Forward",
    callsign: "FOLK",
    frequency: 94.9,
    band: "FM",
    city: "San Francisco",
    genre: "Folk",
    streamUrl: "https://ice1.somafm.com/folkfwd-128-mp3",
  },
];

export function findStation(id: string) {
  return stations.find((s) => s.id === id);
}

export function stationsOnBand(band: Band) {
  return stations.filter((s) => s.band === band);
}
